#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_FPC_TEE)	+= fpc_tee/
obj-$(CONFIG_FINGERPRINT_GOODIX_TA)	+= goodix_ta/
obj-$(CONFIG_FINGERPRINT_SYNAPTICS4302)	+= synaptics/
obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208_C6)	+= goodix_mido/
obj-$(CONFIG_FINGERPRINT_FPC1020_C6)		+= fpc_mido/
